name: build
run-name: Building hardened ISO images
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Make the script executable
        run: chmod u+x ./scripts/build.sh
      - name: Run a script
        run: ./build.sh

