name: build
run-name: Create patched ISO images
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Make the build script executable
        run: chmod u+x scripts/build.sh
      - name: Install dependent packages
        run: sudo apt install -y p7zip-full p7zip-rar genisoimage fakeroot xorriso isolinux binutils squashfs-tools
      - name: Run the build script
        run: scripts/build.sh
      - name: Upload the vault-ubuntu-minimal artifact
        uses: actions/upload-artifact@v4
        with:
          name: vault-ubuntu-minimal
          path: vault-ubuntu-minimal.iso
