name: release
run-name: Create a new release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Download the vault-ubuntu-minimal artifact
        uses: actions/download-artifact@v4
        with:
          name: vault-ubuntu-minimal
      - name: Create a new release with latest images for all OSes
        uses: softprops/action-gh-release@v2
        with:
          files: vault-ubuntu-minimal.iso
